require 'rubygems'
require 'gemspec'



gem 'kramdown'


gem 'octokit', '~> 4.14.0'

gem 'rubocop', '~> 0.71'

gem 'rubocop-rails_config'

gem 'carrierwave', '>= 2.0.0.rc', '< 3.0'

gem 'dropzonejs-rails'

# Octokit does not work with the most recent version of faraday so this locks it to a version that works.
gem 'faraday', '~> 0.17.1'
